language: generic

sudo: required
services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - service docker restart
  - docker build -t ehsan5505/docker-react -f Dockerfile.dev .

script:
  - docker run ehsan5505/docker-react npm run test -- --coverage  
