language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ehsan5505/docker-react -f Dockerfile.dev .

script:
  - docker run ehsan5505/docker-react npm run test -- --coverage  
