language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ehsan5505/docker-react -f Dockerfile.dev .

script:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > $tmpdaemon
  - sudo mv $tmpdaemon /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info
  - docker run ehsan5505/docker-react npm run test -- --coverage  

# deploy:
#   provider: "elasticbeanstalk"
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-256282373722"
#   bucket_path: "docker-react"
#   on:
#     branch: master